export const profileSummary = [
  {
    Role: "Mobile Architect",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. <br> Diverse skill set which includes requirement gathering & analysis, technical designs, work breakdown estimations, Development, Unit Testing and Deployment of application. Build release automation with {version_control} version control system. <br> Managed to define and develop reusable mobile components with the team, that is now being used in all new mobile app developments which saves about 30% of work all the time. Primary areas of expertise are {all_stacks}.",

      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Worked across {industry} industries while doing {platforms} implementation and enhancements, effective communication with clients, process optimization and management. Highly experienced mobile architect with a strong background in developing and leading the design and implementation of successful mobile applications. Demonstrated ability to lead cross-functional teams, manage complex projects, and deliver high-quality products on time. Able to work closely with business stakeholders to understand the requirements and goals of a project, and translate those requirements into technical specifications and a roadmap for development.  <br> Built release automation with {version_control} version control system. Primary areas of expertise are {all_stacks}",

      "{total_years} years of experience in {front_end} mobile app development. Rich professional experience across {industry} industries with support to {platforms} implementation and enhancements, effective communication, performance improvements and so on. Highly experienced mobile architect with a strong background in developing and leading the design and implementation of successful mobile applications. Demonstrated ability to lead cross-functional teams, manage complex projects, and deliver high-quality products on time and within budget. <br> Business requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application are my various skill sets. Having abundance experience with {version_control} version control system. Managed to define and develop reusable mobile components with the team, that is now being used in all new mobile app developments which saves about 30% of work all the time. Primary areas of expertise are {all_stacks}",

      "Experienced Mobile Architect with a demonstrated history of working in the {industry} industries. Skilled at building and maintaining positive relationships with clients and stakeholders, and highly adept at identifying and resolving technical challenges. <br> Over {total_years} years of experience in leading the team and managing the resource. Exposure at working with international clients on critical projects and products.<br> Excellent understanding of designing apps using Object Oriented Principles and architecture like MVC and MVVM. Driven project discovery phase to define business objectives, existing system capabilities, mobile requirements and API services<br> Worked closely with Engineering, Marketing, Business Development and Customer Service departments to discover ongoing and future company initiatives for mobile users.<br> Designed technical architecture and presented architecture, goals, progress and milestones to client and company senior management. Primary areas of expertise are {all_stacks}"
      
    ],
  },
  {
    Role: "Lead Xamarin Developer",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries with support to {platforms} implementation and enhancements, effective communication, performance improvements and so on. Demonstrated ability to lead cross-functional teams, manage complex projects, and deliver high-quality products on time and within budget. <br> Business requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application are my various skill sets. Build release automation with {version_control} version control system. Managed to define and develop reusable mobile components with the team, that is now being used in all new mobile app developments which saves about 30% of work all the time. Primary areas of expertise are {all_stacks}.",

      "{total_years} years of experience in {front_end} mobile app development. Rich professional experience across {industry} industries while supporting {platforms} implementation and enhancements, effective communication, performance improvements and so on. Skilled at building and maintaining positive relationships with clients and stakeholders, and highly adept at identifying and resolving technical challenges. Have a strong background in C# programming and a proven track record of effectively leading and managing development teams to successfully deliver complex projects on time and within budget. Have a strong understanding of the full software development life cycle and have successfully managed the development and deployment of multiple Xamarin projects. In addition to my technical expertise, I am an effective communicator and team leader, with a track record of mentoring and motivating team members to deliver their best work. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application. Build release automation with {version_control} version control system. Primary areas of expertise are {all_stacks}.",
    ],
  },
  {
    Role: "Lead React Native Developer",
    Summary: [
      "{total_years} years of experience in {front_end} mobile app development. Rich professional experience across {industry} industries with support to {platforms} implementation and enhancements, effective communication, performance improvements and so on. Demonstrated ability to lead cross-functional teams, manage complex projects, and deliver high-quality products on time and within budget. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application. Build release automation with {version_control} version control system. Managed to define and develop reusable mobile components with the team, that is now being used in all new mobile app developments which saves about 30% of work all the time. Primary areas of expertise are {all_stacks}.",

      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. worked across {industry} industries while supporting the activities such as {platforms} implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. Have a deep understanding of the full software development life cycle, and have successfully managed the development and deployment of multiple React projects. Technical skills include React, Redux, and Node.js, and I have a proven track record of using these technologies to design and implement scalable, reliable, and user-friendly applications. In addition to my technical expertise, I am an effective communicator and team leader, with a track record of mentoring and motivating team members to deliver their best work and also mentor and coach team members, identify and address any risks, and be familiar with React best practices. <br> Business requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application are my various skill sets. Build release automation with {version_control} version control system. Primary areas of expertise are {all_stacks}.",
    ],
  },
  {
    Role: "Lead Flutter Developer",
    Summary: [
      "{total_years} years of experience in {front_end} mobile app development. Rich professional experience across {industry} industries with support to {platforms} implementation and enhancements, effective communication, performance improvements and so on. Demonstrated ability to lead cross-functional teams, manage complex projects, and deliver high-quality products on time and within budget. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application. Build release automation with {version_control} version control system. Managed to define and develop reusable mobile components with the team, that is now being used in all new mobile app developments which saves about 30% of work all the time. Primary areas of expertise are {all_stacks}.",

      "{total_years} years of experience in {front_end} mobile app development. Rich professional experience across {industry} industries with support to {platforms} implementation and enhancements, effective communication, performance improvements and so on. Have a strong understanding of the Dart programming language and the Flutter library, and are skilled in designing and implementing intuitive and functional user interfaces. Have experience with other related technologies such as Firebase, GraphQL. <br> Business requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application are my various skill sets. Used {version_control} as version control systems. Primary areas of expertise are {all_stacks}."

    ],
  },
  {
    Role: "Lead Android Developer",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. Demonstrated ability to lead cross-functional teams, manage complex projects, and deliver high-quality products on time and within budget. <br> Business requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application are my various skill sets. Build release automation with {version_control} version control system. Managed to define and develop reusable mobile components with the team, that is now being used in all new mobile app developments which saves about 30% of work all the time. Primary areas of expertise are {all_stacks}.",

      "{total_years} years of experience in {front_end} mobile app development. Rich professional experience across {industry} industries with support to {platforms} implementation and enhancements, effective communication, performance improvements and so on. Having strong understanding of the Android operating system and the Android software development kit (SDK), and have a proven track record of using those technologies to design and implement scalable, reliable, and user-friendly mobile applications. Have extensive experience in developing and leading cross-functional teams to deliver innovative, high-quality mobile applications for the Android platform.<br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application. Primary areas of expertise are {all_stacks}.",

    ],
  },
  {
    Role: "Lead ios Developer",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. Demonstrated ability to lead cross-functional teams, manage complex projects, and deliver high-quality products on time and within budget. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application. Build release automation with {version_control} version control system. Managed to define and develop reusable mobile components with the team, that is now being used in all new mobile app developments which saves about 30% of work all the time. Primary areas of expertise are {all_stacks}.",

      "{total_years} years of experience in {front_end} mobile app development. Rich professional experience across {industry} industries with support to {platforms} implementation and enhancements, effective communication, performance improvements and so on. Have a strong understanding of the iOS platform, and are skilled in designing and implementing intuitive and functional user interfaces. Have experience with other related technologies such as iOS SDK, and frameworks like Core Data and Core Animation. Skilled at building and maintaining positive relationships with clients and stakeholders, and highly adept at identifying and resolving technical challenges. Have a lot of experience in building innovative, high-performance iOS applications for businesses in a variety of industries.<br> Business requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application are my various skill sets.Primary areas of expertise are {all_stacks}.",
    ],
  },
  {
    Role: "Senior React Native Developer",
    Summary: [
      "{total_years} years of experience in {front_end} mobile app development. Rich professional experience across {industry} industries with support to {platforms} implementation and enhancements, effective communication, performance improvements and so on. <br> Business requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application are my various skill sets. Used {version_control} as version control systems Managed to define and develop reusable mobile components with the team, that is now being used in all new mobile app developments which saves about 30% of work all the time. Primary areas of expertise are {all_stacks}.",

      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. Have a strong understanding of JavaScript and the React library, and are skilled in designing and implementing scalable and efficient user interfaces. Have experience with other related technologies such as Redux, React Router, and GraphQL. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application. Build release automation with {version_control} version control system. Primary areas of expertise are {all_stacks}.",
    ],
  },
  {
    Role: "Senior Xamarin Developer",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application.  Build release automation with {version_control} version control system. Managed to define and develop reusable mobile components with the team, that is now being used in all new mobile app developments which saves about 30% of work all the time. Primary areas of expertise are {all_stacks}.",

      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. Have a strong understanding of the .NET framework and the C# programming language, and are skilled in designing and implementing intuitive and functional user interfaces. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application. Build release automation with {version-control} version control system. Primary areas of expertise are {all_stacks}."
    ],
  },
  {
    Role: "Senior ios Developer",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application.  Build release automation with {version_control} version control system. Managed to define and develop reusable mobile components with the team, that is now being used in all new mobile app developments which saves about 30% of work all the time. Primary areas of expertise are {all_stacks}.",

      "{total_years} years of experience in {front_end} mobile app development. Rich professional experience across {industry} industries with support to {platforms} implementation and enhancements, effective communication, performance improvements and so on. Have a strong understanding of the iOS platform and the Swift or Objective-C programming languages, and are skilled in designing and implementing intuitive and functional user interfaces. Have experience with other related technologies such as iOS SDK, and frameworks like Core Data and Core Animation. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application.  Build release automation with {version_control} version control system. Primary areas of expertise are {all_stacks}.",
    ],
  },
  {
    Role: "Senior Android Developer",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application.  Build release automation with {version_control} version control system. Managed to define and develop reusable mobile components with the team, that is now being used in all new mobile app developments which saves about 30% of work all the time. Primary areas of expertise are {all_stacks}.",

      "{total_years} years of experience in {front_end} mobile app development. Rich professional experience across {industry} industries with support to {platforms} implementation and enhancements, effective communication, performance improvements and so on. Have a strong understanding of the Android platform and the Java programming language, and are skilled in designing and implementing intuitive and functional user interfaces. Have experience with other related technologies such as Android Studio, the Android SDK, and Android Jetpack. <br> Business requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application are my various skill sets. Primary areas of expertise are {all_stacks}.",
    ],
  },
  {
    Role: "Senior Flutter Developer",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application.  Build release automation with {version_control} version control system. Managed to define and develop reusable mobile components with the team, that is now being used in all new mobile app developments which saves about 30% of work all the time. Primary areas of expertise are {all_stacks}.",

      "{total_years} years of experience in {front_end} mobile app development. Rich professional experience across {industry} industries with support to {platforms} implementation and enhancements, effective communication, performance improvements and so on. Have a strong understanding of the Dart programming language and the Flutter library, and are skilled in designing and implementing intuitive and functional user interfaces. Have experience with other related technologies such as Firebase, GraphQL, and Android Studio or Visual Studio Code. <br> Business requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application are my various skill sets. Worked on {version_control} version control system. Primary areas of expertise are {all_stacks}.",
    ],
  },
  {
    Role: "Junior Flutter Developer",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} App Development & implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application to Business users. Build release automation with {version_control} version control system. Primary areas of expertise are {all_stacks}.",

      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. Have a strong understanding of the Dart programming language and the Flutter library, and are skilled in designing and implementing intuitive and functional user interfaces. Have experience with other related technologies such as Firebase, GraphQL, and Android Studio or Visual Studio Code. <br> Responsible for debugging, troubleshooting, and fixing any issues that arise during the software development lifecycle. Build release automation with {version_control} version control system. Primary areas of expertise are {all_stacks}.",
    ],
  },
  {
    Role: "Junior React Native Developer",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} App Development & implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application to Business users. Build release automation with {version_control} version control system. Primary areas of expertise are {all_stacks}.",

      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. Have a strong foundation in programming concepts and languages, such as JavaScript and React ecosystem, including the React hooks API and the React Router library. <br> Responsible for debugging, troubleshooting, and fixing any issues that arise during the software development lifecycle. Used {version_control} as version control systems. Primary areas of expertise are {all_stacks}.",
    ],
  },
  {
    Role: "Junior Xamarin Developer",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} App Development & implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application to Business users. Build release automation with {version_control} version control system. Primary areas of expertise are {all_stacks}.",

      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} App development & implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. Have a strong understanding of the .NET framework and the C# programming language, and are skilled in designing and implementing intuitive and functional user interfaces. <br> Responsible for debugging, troubleshooting, and fixing any issues that arise during the software development lifecycle. Build release automation with {version_control} version control system. Primary areas of expertise are {all_stacks}.",
    ],
  },
  {
    Role: "Junior Swift Developer",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} App Development & implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application to Business users. Build release automation with {version_control} version control system. Primary areas of expertise are {all_stacks}.",

      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} App development & implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. Have a strong foundation in programming concepts and languages, as well as an understanding of the iOS ecosystem and the tools used to develop iOS applications, such as XCode.  Work with a team of developers to create and improve iOS applications, using programming languages such as Swift or Objective-C. <br> Responsible for debugging, troubleshooting, and fixing any issues that arise during the software development lifecycle. Build release automation with {version_control} version control system. Primary areas of expertise are {all_stacks}.",
    ],
  },
  {
    Role: "Junior Android Developer",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} App Development & implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application to Business users. Build release automation with {version_control} version control system. Primary areas of expertise are {all_stacks}.",

      "{total_years} experience in Mobile Application development using {front_end}, have worked with clients across {industry} industries while supporting the activities such as {platform} App Development & Implementations and enhancements. have involved in effective communication with multiple Project Managers & offshore teams and suggested process optimizations & performance improvements. Have an understanding of the Android ecosystem, including the Android Studio integrated development environment (IDE) and the Android Software Development Kit (SDK). Works with a team of developers to create and improve applications for the Android operating system, which is used on a wide range of devices including smartphones, tablets, and wearable devices. <br> Responsible for debugging, troubleshooting, and fixing any issues that arise during the software development lifecycle. Primary areas of expertise are {all_stacks}.",
    ],
  },
  {
    Role: "Lead",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} App Development & implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. Highly experienced in leading the design and implementation of successful applications. Demonstrated ability to lead cross-functional teams, manage complex projects, and deliver high-quality products on time and within budget. <br> Business requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application are my various skill sets. Build release automation with {version_control} version control system. Managed to define and develop reusable components with the team, that is now being used in all new developments which saves about 30% of work all the time. Primary areas of expertise are {all_stacks}.",
      
    ],
  },
  {
    Role: "Senior",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} App Development & implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application.  Build release automation with {version_control} version control system. Managed to define and develop reusable components with the team, that is now being used in all new developments which saves about 30% of work all the time. Primary areas of expertise are {all_stacks}.",
    ],
  },
  {
    Role: "Junior",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} App Development & implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application to Business users. Build release automation with {version_control} version control system. Primary areas of expertise are {all_stacks}.",
    ],
  },
  {
    Role: "None",
    Summary: [
      "{total_years} years of experience in designing and developing Mobile applications using {front_end}. Rich professional experience across {industry} industries while supporting the activities such as {platforms} App Development & implementation and enhancements, effective communication with stakeholders and team, process optimization and performance improvements. <br> Diverse skill set that includes requirement gathering & analysis, technical design, work breakdown estimations, Development, Unit Testing and Deployment of application. Build release automation with {version_control} version control system. <br> Managed to define and develop reusable components with the team, that is now being used in all new developments which saves about 30% of work all the time. Primary areas of expertise are {all_stacks}.",
    ],
  },
];


